### ISSUE TITLE
FIXME warnings should (optionally) not fail build on Github Integration

### ISSUE THREAD

**Issue by abritinthebay** [codeclimate/codeclimate-fixme#42]
When running a build it would be great to be able to still have FIXME issues noted in the CodeClimate build but not have it fail the build (they are often used to note known issues that may have tech debt tickets or just show there is intent to refactor and to point it out easily).

It's great to have that feature in really strict integration but it would be wonderful to turn that off - without turning FIXME validation off.

Thoughts?

**Comment by pbrisbin** [comment]
Hi @abritinthebay thanks for the suggestion -- we do have some thoughts about making when and how to fail a PR status much more configurable. We'll definitely keep this use-case in mind as we begin work on that feature. I'm going to go ahead and close this issue, since what we'll build would be more generic and an Issue on a specific engine's repository is not the best place to track it. Thanks.

**Comment by abritinthebay** [comment]
Fair enough! For future reference - is there a public repo that would be best for this sort of issue?

**Comment by pbrisbin** [comment]
That's a good question, unfortunately without a direct answer. In this case I think it was totally fine for you to open here to get this conversation going (don't let the fact that I closed the Issue deter that). For overall issues related to our CLI, its repo (`codeclimate/codeclimate`) would be best, but since this is related to our hosted product which is backed by a number of (closed source) services, there's no good place for that.

**Comment by abritinthebay** [comment]
Ahh... gotcha.

Yeah, in this case it seemed like the closest thing to comment on, but obviously not the exact right place. It's frustrating a little because it's getting to the point where we're, as a group, ignoring Code Climate failures on a PR because all it takes is someone changing the line number of a TODO and it will fail.

Obviously that's a bad habit, but we don't want to remove TODO's as they are important to remind us (or tell us that we should have a ticket for things if we don't)

**Comment by pbrisbin** [comment]
Yeah, I'm sorry. We struggle a little with that pain, but on the other hand it has been a good motivator for us to not introduce new TODOs and to go ahead and address existing ones if we end up failing a PR by moving a line -- though we don't find that happening frequently, actually.

**Comment by abritinthebay** [comment]
Oh I agree with it in principle, but it's nice to link Tickets to code as well like "yeah, this is out of scope but I opened a ticket". Usually something like `// TODO - fix Foo ticket ID-1234` can be very helpful both in not having duplicate issues and being clear in terms of scope.
